file(GLOB_RECURSE DEMO_PY_FILES_PY "${CMAKE_SOURCE_DIR}/demo/**/*.py")
file(GLOB_RECURSE DEMO_PY_FILES_TXT "${CMAKE_SOURCE_DIR}/demo/**/*.txt")
set(DEMO_PY_FILES ${DEMO_PY_FILES_PY} ${DEMO_PY_FILES_TXT})
if(DEMO_PY_FILES)
    foreach(PY_FILE ${DEMO_PY_FILES})
        file(RELATIVE_PATH RELATIVE_PATH_TO_DEMO "${CMAKE_SOURCE_DIR}/demo" ${PY_FILE})
        set(TARGET_PY_FILE "${CMAKE_BINARY_DIR}/demo/${RELATIVE_PATH_TO_DEMO}")
        get_filename_component(TARGET_PY_DIR "${TARGET_PY_FILE}" DIRECTORY)
        file(MAKE_DIRECTORY ${TARGET_PY_DIR})
        file(COPY ${PY_FILE} DESTINATION ${TARGET_PY_DIR})
        message(STATUS "Copied ${PY_FILE} to ${TARGET_PY_DIR}")
    endforeach()
else()
    message(STATUS "No Python files found in demo directory.")
endif()
