if(EXISTS "${CMAKE_SOURCE_DIR}/demo")
    file(GLOB_RECURSE DEMO_FILES "${CMAKE_SOURCE_DIR}/demo/**/*.cpp")
    if(DEMO_FILES)
        foreach(CPP_FILE ${DEMO_FILES})
            file(RELATIVE_PATH RELATIVE_PATH_TO_DEMO "${CMAKE_SOURCE_DIR}/demo" ${CPP_FILE})
            get_filename_component(RELATIVE_DIR "${RELATIVE_PATH_TO_DEMO}" DIRECTORY)
            get_filename_component(EXECUTABLE_NAME ${CPP_FILE} NAME_WE)
            if("${EXECUTABLE_NAME}" MATCHES "^test_")
                set(OUTPUT_DIR "${CMAKE_BINARY_DIR}/bin")
            else()
                set(OUTPUT_DIR "${CMAKE_BINARY_DIR}/demo/${RELATIVE_DIR}")
            endif()
            file(MAKE_DIRECTORY "${OUTPUT_DIR}")
            add_executable(${EXECUTABLE_NAME} ${CPP_FILE})
            set_target_properties(${EXECUTABLE_NAME} PROPERTIES RUNTIME_OUTPUT_DIRECTORY "${OUTPUT_DIR}")
            target_link_libraries(${EXECUTABLE_NAME} PRIVATE project_warnings)
            if(TARGET MyProjectLib)
                target_link_libraries(${EXECUTABLE_NAME} PRIVATE MyProjectLib)
            endif()
            message(STATUS "Created executable: ${EXECUTABLE_NAME} from ${CPP_FILE}, output to ${OUTPUT_DIR}")
        endforeach()
    else()
        message(STATUS "demo directory exists but contains no .cpp files. No executables will be built.")
    endif()
else()
    message(STATUS "demo directory does not exist. No executables will be built.")
endif()
