set(LIBRARY_OUTPUT_DIR "${CMAKE_BINARY_DIR}/lib")
set(ENV{LD_LIBRARY_PATH} "${LIBRARY_OUTPUT_DIR}:$ENV{LD_LIBRARY_PATH}")
message(STATUS "LD_LIBRARY_PATH is set to: $ENV{LD_LIBRARY_PATH}")

file(GLOB BST_SRC_FILES "${CMAKE_SOURCE_DIR}/src/lib/bst_api.cpp")
if(BST_SRC_FILES)
    add_library(bstapi SHARED ${BST_SRC_FILES})
    target_include_directories(bstapi PUBLIC ${INCLUDE_ROOT})
    target_link_libraries(bstapi PRIVATE project_warnings)
    set(CMAKE_BUILD_WITH_INSTALL_RPATH TRUE)
    set_target_properties(bstapi PROPERTIES LIBRARY_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/lib")
    message(STATUS "Built shared library: bst.so in ${CMAKE_BINARY_DIR}/lib")
else()
    message(WARNING "No BST source files found. Skipping bst.so compilation.")
endif()

file(GLOB SORT_SRC_FILES "${CMAKE_SOURCE_DIR}/src/lib/sort_api.cpp")
if(SORT_SRC_FILES)
    add_library(sort SHARED ${SORT_SRC_FILES})
    target_include_directories(sort PUBLIC ${INCLUDE_ROOT})
    target_link_libraries(sort PRIVATE project_warnings)
    set(CMAKE_BUILD_WITH_INSTALL_RPATH TRUE)
    set_target_properties(sort PROPERTIES LIBRARY_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/lib")
    message(STATUS "Built shared library: sort.so in ${CMAKE_BINARY_DIR}/lib")
else()
    message(WARNING "No SORT source files found. Skipping sort.so compilation.")
endif()
